### ISSUE TITLE
Reputation Actions

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#52]
https://docs.google.com/document/d/1vg95Bw4Pzsqe4DXPusiyD2hAU-HCI-37c0AAZSXxC68/edit?disco=AAAAI3OMnrg

- [ ] getting vouched
- [ ] rating
- [ ] cast trust tokens
- [ ] delegate trust
- [ ] representative votes
- [ ] funded proposal
- [ ] failed - funded proposal
- [ ] forum up / down votes
- [ ] vouched user becomes resident
- [ ] vouched user becomes citizen
- [ ] vouched user penalized

**Comment by IanMendozaJaimes** [comment]
Hello, I have some questions:
1. What does rating a user means?, I mean, how a user is affected when another user calls rate action?
2. Trust tokens are the same as voice?, if they are, the user should gain reputation each time the action `updatevoices` is called (if the action updates its voice)?
3. Is delegate trust functionality implemented? I couldn't find it in the code
4. For the proposals, I think they are already giving rep to a user if the proposal passes, but there is no method to check if a funded proposal fails, should I implement the method?

**Comment by n13** [comment]
> Hello, I have some questions:
> 
> 1. What does rating a user means?, I mean, how a user is affected when another user calls rate action?

I don't see other references or explanations for ratings - other than rating orgs. Let's skip that for now and I'll check with Rieki. 

> 2. Trust tokens are the same as voice?, if they are, the user should gain reputation each time the action `updatevoices` is called (if the action updates its voice)?

We have already implemented that - if a user votes for all proposals, they get reputation. That's done.

> 3. Is delegate trust functionality implemented? I couldn't find it in the code

No, not yet implemented - it's targeted for end of year when it becomes more relevant and the whole system is running. Skip for now. 

> 4. For the proposals, I think they are already giving rep to a user if the proposal passes, but there is no method to check if a funded proposal fails, should I implement the method?

No we will have to do this along with all the other proposal changes. It's part of the refactoring. We will split proposals into 3 different pieces of functionality - storing a document (doc structure), voting - assigning voice and vote rules, and execution. 

It will work like this:
- When a proposal passes, 10% are paid out immediately
- Each cycle thereafter as long as the prop stays in the passed state, more funds are released
- Those people who voted for the proposal can change their yes to a no - no one else gets to vote on it
- If the proposal gets de-funded, the sponsor loses a significant amount of reputation - failed to follow through as above.

So we don't need to do this for now

**Comment by juliolrmonteiro** [comment]
Regarding losing Rep for failed proposals, it looks the percentage payouts are not checking if the number of positive votes decreased to zero (voters retracted their vote) thus failing the proposal, and then causing the -100 Rep change.

Peer to peer user rating is still not implemented too, right?

And finally, vouch user being penalized looks like to be missing still (is this penality done?)
